# Generated by Django 4.0.5 on 2022-06-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantitiy',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
